// src/components/Icons.tsx

import {
  EyeIcon,
  EyeSlashIcon,
  UserIcon,
  Squares2X2Icon,
  Bars3BottomLeftIcon,
  Cog6ToothIcon,
  Bars3Icon,
  XMarkIcon,
  AdjustmentsHorizontalIcon,
  PlusCircleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ArrowRightOnRectangleIcon,
  PencilSquareIcon,
  TrashIcon,
  CheckIcon,
  HomeIcon,
  StarIcon,
  ArrowUturnLeftIcon,
  ArrowRightIcon,
  PencilIcon,
  LockClosedIcon,
  EnvelopeIcon,
} from '@heroicons/react/24/outline';

export const Icons = {
  Eye: EyeIcon,
  EyeOff: EyeSlashIcon,
  User: UserIcon,
  Kanban: Squares2X2Icon,
  List: Bars3BottomLeftIcon,
  Settings: Cog6ToothIcon,
  Menu: Bars3Icon,
  Close: XMarkIcon,
  Filter: AdjustmentsHorizontalIcon,
  Add: PlusCircleIcon,
  Down: ChevronDownIcon,
  Right: ChevronRightIcon,
  Logout: ArrowRightOnRectangleIcon,
  EditSquare: PencilSquareIcon,
  Trash: TrashIcon,
  Check: CheckIcon,
  Home: HomeIcon,
  Star: StarIcon,
  Back: ArrowUturnLeftIcon,
  ArrowRight: ArrowRightIcon,
  Edit: PencilIcon,
  Lock: LockClosedIcon,
  Mail: EnvelopeIcon,
};
